## PHB 221: Geographic Trends in Heart Disease Mortality

## Introduction


In the research field, there is a strong focus on cancer as a public health concern, but we can’t forget that heart disease still remains as one of the main leading causes of deaths in the United States. According to the Centers for Disease Control and Prevention (CDC), heart disease is the leading cause of death across most racial and ethnic groups, which is responsible for about 1 in every 5 deaths.

For our project, we will analyze publicly available data from the National Center for Health Statistics (NCHS), specifically on the “NCHS - Leading Causes of Death: United States” dataset. Our main focus will be to analyze state level patterns in age adjusted death rates for heart disease over time, and see if there are significant differences across states and regions.

From this dataset, its features include year, state, number of deaths, and age adjusted death rates. We will go through two main research questions, one being an inferential analysis and the other being predictive modeling.

## Main Question

1. Do age adjusted heart disease death rates significantly differ in different states/regions as they change over time?
2. Can past trends in age adjusted heart disease death rates be used to predict future state level rates?

## Exploratory Analysis

In [ ]:
# libraries Needed

import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [14]:
# load data
data = pd.read_csv('NCHS_-_Leading_Causes_of_Death__United_States.csv')

# check data dimension, shape
shape = data.shape

print(f"Data Shape: {shape}")

# check for any missing values
missing_values = data.isnull().sum()
print(f"Missing Values:\n{missing_values}")

Data Shape: (10868, 6)
Missing Values:
Year                       0
113 Cause Name             0
Cause Name                 0
State                      0
Deaths                     0
Age-adjusted Death Rate    0
dtype: int64

In [ ]:
# all different types of column outputs for Cause Name
data["Cause Name"].unique()

array(['Unintentional injuries', 'All causes', "Alzheimer's disease",
       'Stroke', 'CLRD', 'Diabetes', 'Heart disease',
       'Influenza and pneumonia', 'Suicide', 'Cancer', 'Kidney disease'],
      dtype=object)

In [4]:
# preview data
data.head()

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
0,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,United States,169936,49.4
1,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alabama,2703,53.8
2,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Alaska,436,63.7
3,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arizona,4184,56.2
4,2017,"Accidents (unintentional injuries) (V01-X59,Y8...",Unintentional injuries,Arkansas,1625,51.8

In [ ]:
# check specifically for Cause Name Heart Disease and State United States
heart_disease_data = data[(data['Cause Name'] == 'Heart disease') & (data['State'] == 'United States')]
heart_disease_data

,Year,113 Cause Name,Cause Name,State,Deaths,Age-adjusted Death Rate
312,2017,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,647457,165.0
929,2016,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,635260,165.5
1501,2015,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,633842,168.5
2074,2014,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,614348,167.0
2648,2013,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,611105,169.8
3220,2012,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,599711,170.5
3793,2011,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,596577,173.7
4365,2010,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,597689,179.1
4953,2009,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,599413,182.8
5527,2008,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,616828,192.1
6076,2007,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,616067,196.1
6648,2006,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,631636,205.5
7220,2005,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,652091,216.8
7792,2004,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,652486,221.6
8364,2003,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,685089,236.3
8936,2002,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,696947,244.6
9508,2001,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,700142,249.5
10080,2000,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,710760,257.6
10652,1999,"Diseases of heart (I00-I09,I11,I13,I20-I51)",Heart disease,United States,725192,266.5

# next steps?

- clean data
- group data by region?

In [ ]:
# group by region

## Initial Analysis

## Next Steps